name: Run Web Testing Robot
run-name: On Push - Web Tests Run
on: 
  push:
    branches:
    - main
  pull_request:
    branches: [main]
jobs:
  test:
    run-on: ubuntu-20.04
    steps:
    - run: echo "Apenas um teste!"